### ISSUE TITLE
idot.

### ISSUE THREAD

**Issue by ProDev76** [rovelstars/reejs#1]
in getJsxPage.js you eval the raw response of the fetch request you bozo.
imagine if the response is somehow spoofed, then what?
ah yes lets just do some funny stuff.

also define standards for issuses and docs

**Comment by renhiyama** [comment]
Oh I forgot to delete that getJsxPage file 😅. I used eval during the initial time because I was still working on some extra stuff and didn't knew about the feature `await import(url)`. Now this feature is used instead of eval. Enjoy!

Also for defining standards, soon™ !
