### ISSUE TITLE
Add prettier config

### ISSUE THREAD

**Issue by renhiyama** [rovelstars/reejs#17]
Title says it all.

**Comment by Bibek99** [comment]
@renhiyama Shall I take this one ?

**Comment by Timonwa** [comment]
No problem. 👍🏾

**Comment by renhiyama** [comment]
Someone got a lucky day haha

**Comment by renhiyama** [comment]
GG!

**Comment by renhiyama** [comment]
@Bibek99 you can star this repo btw, if you want to

**Comment by Bibek99** [comment]
@renhiyama sure.
